on:
    push:
        tags:
            - "v*" # Push events to every tag not containing /
    workflow_dispatch:

name: Publish

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            CARGO_TERM_COLOR: always
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: Bump version
              uses: cute-lights/bump-version@main
              with:
                  files: "Cargo.toml"

            - name: Publish to crates.io
              run: |
                  git add . 
                  cargo publish ---allow-dirty
              env:
                  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
