on:
    push:
        tags:
            - "v*" # Push events to every tag not containing /
    workflow_dispatch:

name: Publish

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            CARGO_TERM_COLOR: always
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Bump version
              uses: tj-actions/cargo-bump@v3

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5

            - name: Publish to crates.io
              run: cargo publish --token ${CRATES_TOKEN}
              env:
                  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
